# ⚒ Build the builder image
FROM node:18-bullseye

# 👇 Create working directory and assign ownership
WORKDIR /code

# 👇 Copy config files and source
COPY package*.json tsconfig.json ./

# 👇 Install deps and build source
RUN npm install

COPY src ./src

CMD ["npm", "run", "start:dev"]